### PR TITLE
Proofread & Organized (BRANCH: master)

### PR DESCRIPTION
**Pull request by Kenner-G**

### CODE REVIEW

**Comment by TheNewHEROBRINEX** [comment]
Dev branch will be merged into master soon so this is not necessary

**Comment by TheNewHEROBRINEX** [comment]
Can you remake this pull request? I deleted your commit by mistake

**Comment by Kenner-G** [comment]
@TheNewHEROBRINEX can you add a new branch named "English" and merge master into it? I'll edit English and make sure it is 100% correct.

**Comment by TheNewHEROBRINEX** [comment]
https://github.com/TheNewHEROBRINEX/Murder/tree/english

**Pull request closed without merging**
